Add spacing after comments, Rename restexceptions.py

diff --git a/src/scripts/initscript/debian/plivo-myscript b/src/scripts/initscript/debian/plivo-myscript
--- a/src/scripts/initscript/debian/plivo-myscript
+++ b/src/scripts/initscript/debian/plivo-myscript
@@ -11,7 +11,6 @@
 # Description:       This file provides a template for creating plivo init scripts.
 ### END INIT INFO
 
-# Author: Michael Ricordeau <michael.ricordeau@gmail.com>
 
 
 #######################################
@@ -62,12 +61,12 @@ DAEMON_ARGS="-u $USER -g $GROUP -p $PIDFILE -s $SCRIPT -a \"$SCRIPTARGS\""
 #
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
         kill -0 $(cat $PIDFILE 2>/dev/null) && return 1;
-        $DAEMON $DAEMON_ARGS                        
+        $DAEMON $DAEMON_ARGS
         sleep 0.5
         kill -0 $(cat $PIDFILE 2>/dev/null) && return 0 || return 2;
 }
@@ -77,24 +76,24 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
         # If no pidfile or pidfile is empty, return failure (2)
         [ ! -s $PIDFILE ] && return 2;
         # If process is not running, return already stopped (1)
         kill -0 $(cat $PIDFILE 2>/dev/null) && return 1;
         # Kill with SIGTERM (30 retries) and return 0 on success
         for i in $seq(1 1 30); do
-                kill -TERM $(cat $PIDFILE 2>/dev/null) 
+                kill -TERM $(cat $PIDFILE 2>/dev/null)
                 kill -0 $(cat $PIDFILE 2>/dev/null) && rm -f $PIDFILE && return 0;
                 sleep 0.1
         done
         # Kill with SIGKILL if already running (5 retries) and return 0 on success
         for i in $(seq 1 1 5); do
-                kill -KILL $(cat $PIDFILE 2>/dev/null) 
+                kill -KILL $(cat $PIDFILE 2>/dev/null)
                 kill -0 $(cat $PIDFILE 2>/dev/null) && rm -f $PIDFILE && return 0;
                 sleep 0.1
         done
@@ -106,67 +105,67 @@ do_stop()
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	return 0
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    return 0
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INITSCRIPT"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INITSCRIPT"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INITSCRIPT"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INITSCRIPT"
+    do_stop
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    #log_daemon_msg "Reloading $DESC" "$NAME"
+    #do_reload
+    #log_end_msg $?
+    #;;
   restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$INITSCRIPT"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    log_daemon_msg "Restarting $DESC" "$INITSCRIPT"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
+    ;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
-	exit 3
-	;;
+    #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
 
 :
